name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update package lists
      run: sudo apt-get update

    - name: Install required packages
      run: |
        sudo apt-get install -y build-essential curl git

    - name: Use Node.js 14.x
      uses: actions/setup-node@v4
      with:
          node-version: 14.x
          
    - name: Download Python 2.7
      run: wget https://www.python.org/ftp/python/2.7/Python-2.7.tgz -P /tmp

    - name: Extract Python 2.7
      run: tar -xzf /tmp/Python-2.7.tgz -C /tmp

    - name: Configure and install Python 2.7
      run: |
        cd /tmp/Python-2.7
        ./configure
        make
        sudo make install

    - name: Install Node.js dependencies
      run: npm install
      working-directory: ./front

    - name: Remove current version of Google Chrome
      run: |
        sudo apt-get remove google-chrome-stable
        sudo apt-get autoremove
        sudo apt-get clean
        
    - name: Install Chrome
      run: |
        sudo apt-get install -y google-chrome-stable=114.0.5735.90

    - name: Build
      run: npm run build
      working-directory: ./front

    - name: Unit tests
      run: npm run test
      working-directory: ./front
      
    - name: Run end-to-end tests
      run: npm run e2e
      working-directory: ./front
